config/routes.rb
ExchangeSubject::Application.routes.draw do
  resources :proposals do
    member do
      post 'accept'
      post 'cancel'
    end

    collection do
      get 'overview'
    end
  end

  get "welcome/index"
  devise_for :users

  root 'welcome#index'

  

end

app/models/day.rb
class Day < ActiveRecord::Base
	has_many :terms

	def to_s
		name
	end
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  belongs_to :term
  belongs_to :user

  validate :one_proposal_for_term
  validate :one_not_preferred_proposal_for_subject
  validate :one_accepted_for_subject

  belongs_to :accepted, foreign_key: 'accepted_id', class_name: 'Proposal'

  def to_s
  	is_preferred = preferred ? "preferred" : "not preferred"
  	"#{term} (#{is_preferred})"
  end

  delegate :subject, to: :term

  def one_proposal_for_term
  	if user.proposals.where(term: term).where.not(id: id).count > 0
  		errors.add(:term, "is already occupied")
  	end
  end

  def one_not_preferred_proposal_for_subject
  	if !preferred and user.proposals.joins(:term).where(preferred: false, terms: { subject_id: subject.id }).where.not(id: id).count > 0
  		errors.add(:term, "for this subject already exists one which is not preferred")
  	end
  end

  def one_accepted_for_subject
    if accepted_id and user.proposals.joins(:term).where(terms: { subject_id: subject.id }).where.not(id: id, accepted_id: nil).count > 0
      errors.add(:term, "for this subject one term was already accepted")
    end
  end

  def self.all_matches
    select('a.*').from('proposals AS a').joins('inner join proposals AS b ON a.accepted_id = b.id and b.accepted_id = a.id and a.id > b.id')
  end

end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :terms

	def to_s
		name
	end

	def match(user)
		matches = []

		u_term_to_give = user.terms.find_by(subject: self, proposals: { preferred: false }) # p0
		u_terms_to_take = user.terms.where(subject: self, proposals: { preferred: true }) # p1..pn
 
		if u_term_to_give and u_terms_to_take.any?
			potential_takers = u_term_to_give.proposals.where(preferred: true).map { |p| p.user }
			potential_takers.each do |v|
				v_terms_to_give = v.terms.find_by(subject: self, proposals: { preferred: false }) # q0
				if u_terms_to_take.include?(v_terms_to_give)
					matches << v.to_give(self)
				end
			end
		end

		return matches
	end
end

app/models/term.rb
class Term < ActiveRecord::Base
  belongs_to :day
  belongs_to :subject

  has_many :proposals
  has_many :users, through: :proposals

  def to_s
  	"#{subject}, #{day} at #{hour.strftime("%H:%M")}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :proposals
  has_many :terms, through: :proposals

  def to_s
  	email
  end

  def subjects_to_exchange
  	terms.map(&:subject).uniq
  end

  def to_give(subject)
    proposals.joins(:term).find_by(terms: { subject_id: subject.id }, preferred: false)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_proposal, only: [:show, :edit, :update, :destroy, :accept, :cancel]
  before_filter :authenticate_user!

  http_basic_authenticate_with name: "admin", password: "admin", only: :overview

  # GET /proposals
  # GET /proposals.json
  def index
    @proposals = current_user.proposals
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
  end

  # GET /proposals/new
  def new
    @proposal = Proposal.new
  end

  # GET /proposals/1/edit
  def edit
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = current_user.proposals.build(proposal_params)

    respond_to do |format|
      if @proposal.save
        format.html { redirect_to @proposal, notice: 'Proposal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @proposal }
      else
        format.html { render action: 'new' }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proposals/1
  # PATCH/PUT /proposals/1.json
  def update
    respond_to do |format|
      if @proposal.update(proposal_params)
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html { redirect_to proposals_url }
      format.json { head :no_content }
    end
  end

  def accept
    @proposal.accepted_id = params[:accepted_id]
    if @proposal.save
      redirect_to proposals_path, notice: "Proposal was accepted."
    else
      redirect_to proposals_path, notice: "Something went wrong..."
    end
  end

  def cancel
    @proposal.accepted_id = nil
    if @proposal.save
      redirect_to proposals_path, notice: "Proposal was cancelled."
    else
      redirect_to proposals_path, notice: "Something went wrong..."
    end
  end

  def overview
    @matches = Proposal.all_matches
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proposal
      @proposal = current_user.proposals.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proposal_params
      params[:proposal].permit(:term_id, :preferred, :reason)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Terms Exchange" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Terms Exchange</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", root_path  %></li>
              <li><%= link_to "Proposals", proposals_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

       <%= bootstrap_flash %>
      <%= yield %>
         
      <footer>
        <p></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/proposals/_form.html.erb
<%= simple_form_for @proposal, html: {class: 'form-horizontal' } do |f| %>
	<%= f.error_notification %>

	<%= f.association :term, collection: Subject.all, as: :grouped_select, group_method: :terms %>
	<%= f.input :preferred %>
	<%= f.input :reason %>

	<%= f.button :submit %>

<% end %>

app/views/proposals/edit.html.erb
<h1>Editing proposal</h1>

<%= render 'form' %>

<%= link_to 'Show', @proposal %> |
<%= link_to 'Back', proposals_path %>

app/views/proposals/index.html.erb
<h1>Listing proposals</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Term</th>
      <th>State</th>
      <th>Reason</th>
      <th>Options</th>
    </tr>
  </thead>

  <tbody>
    <% @proposals.each do |proposal| %>
      <tr>
        <td><%= proposal.term %></td>
        <td><%= proposal.preferred ? "preferred" : "not preferred" %></td>
        <td><%= proposal.reason %></td>
        <td><%= link_to 'Show', proposal %> 
        <%= link_to 'Edit', edit_proposal_path(proposal) %> 
        <%= link_to 'Destroy', proposal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proposal', new_proposal_path %>


<h1>Your matches</h1>

<% Subject.all.each do |s| %>
  <% to_give = current_user.to_give(s) %>
  <% if to_give %>
    <% s.match(current_user).each do |match| %>
      <%= "Found #{match.term} with #{match.user}" -%> 
      <% if to_give.accepted %>
        <% if match.accepted == to_give %>
          Terms exchenaged successfully!
        <% else %>
          (waiting for the other side acceptance...) <%= button_to "cancel", cancel_proposal_path(to_give), method: :post -%>
        <% end %>
      <% else %>
        <%= form_tag accept_proposal_path(to_give) do -%>
          <%= hidden_field_tag :accepted_id, match.id %>
          <%= submit_tag "accept" -%>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/proposals/new.html.erb
<h1>New proposal</h1>

<%= render 'form' %>

<%= link_to 'Back', proposals_path %>

app/views/proposals/overview.html.erb
<table class="table table-bordered tabel-striped">
	<% @matches.each do |m| %>
	<tr>
		<td><%= "#{m.user} #{m.term}" %></td>
		<td><%= "#{m.accepted.user} #{m.accepted.term}" %></td>
	</tr>
	<% end %>
</table>

app/views/proposals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<%= @proposal %>
</p>


<%= link_to 'Edit', edit_proposal_path(@proposal) %> |
<%= link_to 'Back', proposals_path %>

app/views/welcome/index.html.erb
<h1>Welcome aboard! </h1>

<p>
	<% if signed_in? %>
		You are signed in as <%= current_user.email %> |
		<%= link_to 'Sign out', destroy_user_session_path, method: :delete %> 
	<% else %>
		<%= link_to 'Sign in', new_user_session_path %> 
	<% end %>
</p>